### ISSUE TITLE
Sourcemaps being added to production file.

### ISSUE THREAD

**Issue by stephenprovenzano** [maxlapides/dovetailer#15] opened 2017-03-02 22:21 UTC
I'm noticing sourcemaps being added to the final production html files in the build folder. This is increasing file-size dramatically.

**Comment by maxlapides** [comment] 2017-03-05 23:21
@stephenprovenzano i can't reproduce this issue. i don't see any sourcemaps in the final build files, only in the development versions. i'm going to close this issue for now, please re-open if you can provide steps to reproduce.

**Closed by maxlapides** 2017-03-05 23:21 UTC
