### ISSUE TITLE
ESP Merge tags / Dynamic data being removed from anchor tags.

### ISSUE THREAD

**Issue by stephenprovenzano** [maxlapides/dovetailer#10] opened 2017-02-10 17:58 UTC
We had a section where we needed to call in a dynamic link, the ESP utilizes a similar handlebars data structure. `<a href="{{ Dynamic_Link }}">`.

The compiled file in the build folder would then end up having a blank anchor `<a href></a>`.

The only way we found to work around this issue was to go into the compiled build file and manually re-enter the data.

**Comment by maxlapides** [comment] 2017-02-13 00:29
@stephenprovenzano I wasn't able to reproduce this issue. Can you provide a more complete example? Here's what I tested:

html.handlebars
```
<html>
<body>
    <a href="{{href}}">another link</a>
</body>
</html>
```

content.json
```
{
    "href": "https://fulcrumtech.net"
}
```

**Comment by maxlapides** [comment] 2017-02-13 00:35
@stephenprovenzano Also, I would prefer using markdown for generating links. For example:

html.handlebars
```
<html>
<body>
    {{link}}
</body>
</html>

```

content.json
```
{
    "link": "[another link](https://fulcrumtech.net)"
}
```

**Comment by stephenprovenzano** [comment] 2017-02-13 22:04
@maxlapides Try your method but instead of providing a link, provide a merge tag in the content file.

Example:

content.json

`{
"link": "{{view_online}}",
}`

Then try to apply this data in an anchor's `href=""`

I know the feature was added to embed data into the content file {{}}'s, but perhaps there is an issue with anchors?

**Comment by maxlapides** [comment] 2017-02-21 18:51
@stephenprovenzano unfortunately i still cannot reproduce this issue. here's the test case i used:

content.json
```
{
    "link": "{{view_online}}"
}
```
(note that this is different than your example above because it does not include the trailing comma, which makes the JSON invalid)

html.handlebars
```
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Test</title>
</head>
<body>
    <a href="{{link}}">test</a>
</body>
</html>
```

can you provide a complete test case so I can reproduce?

**Comment by maxlapides** [comment] 2017-03-05 23:19
@stephenprovenzano i'm going to close this issue for now. please re-open if you can provide reproduction steps!

**Closed by maxlapides** 2017-03-05 23:19 UTC
Labels: bug
